server:
  port: 8888
security:
  basic:
    enable: false
spring:
#  rabbitmq:
#    host: 172.16.10.170
#    port: 5672
#    username: admin
#    password: admin
  rabbitmq:
    host: 172.16.15.76
    port: 5672
    username: zxtfadmin
    password: zxtfadmin
#    publisher-confirms: true
#    publisher-returns: true
#    listener:
#      direct:
#        acknowledge-mode: auto
#      simple:
#        acknowledge-mode: auto
  redis:
    host: 172.16.10.170
    port: 6379
    timeout: 5000
    password: 123456
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 165177
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true&charset=utf8mb4&useSSL=false&serverTimezone=UTC
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.demo.jpa.config.JpaConfig
      properties:
        hibernate:
          format_sql: true
          hbm2ddl:
            auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

constant:
  enable: true
logging:
  config: classpath:logback.xml
